events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;   # mapowanie rozszerzeń na Content-Type
    default_type  application/octet-stream;
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=stats_cache:10m max_size=100m inactive=60s;

    server {                    # wirtualny host
        listen      80; # nasluchowanie na porcie 80 (kontener)
        server_name cursoraZadanie.com;

        location /api/stats {
            proxy_pass http://app:3000/stats;

            proxy_cache stats_cache;
            proxy_cache_valid 200 30s;

            add_header X-Cache-Status $upstream_cache_status;
        }

        location /api/ {
            proxy_pass http://app:3000/;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
